### ISSUE TITLE
[BUG] No Curve-Fitted Data Appears after fitting the data, 

### ISSUE THREAD

**Issue by Gianluca2** [teasit/magic-formula-tyre-tool#5]
Hey, It's me again (Sorry), I downloaded the newest version of the program, ran the program and it ran just fine, I managed to get values and applied them as intended. However when I try to see the values found in the graph, nothing happens. I notice that I can only fit the data with FY0. It doesn't let me with FX0.  Any of the Mz0, MX, MY gives an error to which I attached screenshots below. I'm using Run Data 19 from round 8, but tried Run Data 17-23 and got the same error. Is there a way to get the file to be use the FX0 fit mode, like the tutorial video? Thanks for taking the time, this program is really good and got a lot of potential.

![Screenshot 2023-10-18 010908](https://github.com/teasit/magic-formula-tyre-tool/assets/39840319/0ef767a7-66db-4048-b73c-46ef11bc1f80)
![Screenshot 2023-10-18 010931](https://github.com/teasit/magic-formula-tyre-tool/assets/39840319/929d1689-5987-4d76-91e8-fc907621c85f)
![Screenshot 2023-10-18 010957](https://github.com/teasit/magic-formula-tyre-tool/assets/39840319/c3eabdd3-b87e-4f89-80c0-57b2991e3eb2)
![Screenshot 2023-10-18 011528](https://github.com/teasit/magic-formula-tyre-tool/assets/39840319/6d6f8147-b8f7-46be-93c7-7cc6848658d1)

**Comment by teasit** [comment]
Hi @Gianluca2 

The tool works for you with the example data though? Just to make sure the issues are related to the data sets.

There are multiple issues in this post. In the last screenshot, it tells you that you need to set UNLOADED_RADIUS to be able to fit Mz0.

Second plot looks a bit weird because it is Fy over Fz. Not sure why you need it. I honestly only implemented only because I could, not because it is very useful. The plots of Fy over slip angle should be more useful.

First screenshot says that the data did not contain FX fittable steady states. Might just be an import issue. I suggest debugging the import script. With the new version you can press the EDIT button which will take you to the script which does the importing. Then place a debugging point at the start and check what is going wrong. Didn't have the time yet to pursue this issue myself...

**Comment by teasit** [comment]
@Gianluca2 

I tried Run Data 19 and it worked for me. You cannot use it to fit Fx0, because it does not contain data for that.

You can check `RunGuide_Round8.pdf` which comes with the data.
There are two tables. One for cornering, one for drive/brake. You need the latter to be able to fit Fx0/Fx/Fy.

Sadly these are not always available due to the machine at Calspan not being able to handle small tires for those tests.
You can try mixing tire data sets, but that is obviously not ideal.
